Mnaveau/free flyer and com torque
machines-in-motion/mim_control pull request #7
Opened 2021-01-25 09:58 UTC by MaximilienNaveau

[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Description

[//]: # "Description of what you did.  If it is more complex, consider to add a"
[//]: # "'Summary' section."

- Add and fix docstrings.
- Add a `ImpedanceController::get_joint_torques()` method.
- Fix impedance implementation using a sub-kinematic-chain.

## How I Tested

[//]: # "Explain how you tested your changes"

Ran simu on pybullet.

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [ ] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [ ] All new functions/classes are documented and existing documentation is updated according to changes.
- [ ] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

2021-01-25 14:28 UTC, jviereck commented on src/centroidal_force_qp_controller.cpp
> +        double z = relative_position_endeff(3 * i + 2);
Can you remove the comment here?

2021-01-25 14:29 UTC, jviereck commented on src/impedance_controller.cpp
> +        pinocchio_model_.joints[1].shortname() == "JointModelFreeFlyer";
I like this one :)!

2021-01-25 14:36 UTC, jviereck requested changes
Looks good overall with small request.

Are you sure changing the reference frame for the jacobians from LOCAL_WORLD_ALIGNED -> WORLD is the right thing to do? It was working fine before with LOCAL_WORLD_ALIGNED for me.

2021-01-27 18:42 UTC, jviereck commented
Trying to compile this PR, I am getting quite a few errors like this one:

```
/home/jviereck/dev/blmc_testing/workspace/src/mim_control/src/impedance_controller.cpp:130:49: error: no match for ‘operator*’ (operand types are ‘Eigen::Transpose<Eigen::Matrix<double, 6, -1, 0, 6, -1> >’ and ‘pinocchio::Force {aka pinocchio::ForceTpl<double, 0>}’)
     torques_ = (impedance_jacobian_.transpose() * impedance_force_);
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
```

They seem all related to the `impedance_force_` being a `pinocchio::Force` instead of a 6-dim-vector.

2021-01-27 18:57 UTC, jviereck commented
I switched the `impedance_force_` from a `pinocchio::Force` to a `Vector6d`. With this change the code is compiling. However, the robot starts flying away when I try to walk with the changes in simulation.

2021-01-28 12:59 UTC, MaximilienNaveau commented
Sorry this PR is under debug

2021-01-28 13:01 UTC, MaximilienNaveau commented
> Looks good overall with small request.
> 
> Are you sure changing the reference frame for the jacobians from LOCAL_WORLD_ALIGNED -> WORLD is the right thing to do? It was working fine before with LOCAL_WORLD_ALIGNED for me.

I think you did try only using root_frame as "universe" and not the hip or something.
And indeed the code should work for this case but I think there a bug if you try a subkinematic chain

2021-02-02 13:16 UTC, MaximilienNaveau commented
@jviereck I force pushed the PR I just add the get_joint_torques.
There is still an issue if I try to control the foot in the hip frame...
Maybe we should chat about this

2021-02-02 14:58 UTC, jviereck approved these changes
This looks good.

2021-02-02 17:20 UTC, merged